spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
